### ISSUE TITLE
Add an actual bundled usrsctp to psi-plus-snapshots

### ISSUE THREAD

**Issue by lockywolf** [psi-plus/maintenance#21]
HHello
 I am building psi on a machine without git. 
If I set -DBUNDLED_USRSCTP=ON , the build script checks out it from git, which fails on my machine.
Additionnaly, the internet provider I am using is shaping (ofr 'security' reasons) all non-DPI'able connections (that is https and ssh) to ~14k/s, which makes git checkouts at build time a stopper for the build process.

Could usrsctp be actually bundled in?

**Comment by tehnick** [comment]
> Could usrsctp be actually bundled in?

No. Use system version of this library if you build Psi+ in Linux.
